<a href="#Objet Image DOM">Objet image DOM</a>
<a href="#Créer un objet image">Créer un objet image</a>
<a href="#Objet form du DOM">Objet form du DOM</a>
<a href="#Créer un objet form">Créer un objet form</a>
<a href="#Exercice 1">Exercice 1</a>
<a href="#Collection d'éléments">Collection d'éléments</a>
<a href="#Exercice 2">Exercice 2</a>
<a href="#Exercice 3">Exercice 3</a>
<a href="#Validation de formulaire">Validation de formulaire</a>
<a href="#Exercice 4">Exercice 4</a>
<a href="#Validation automatique">Validation automatique</a>
<a href="#Validation des contraintes">Validation des contraintes</a>
<a href="#L'attribut readonly">L'attribut readonly</a>
<a href="#L'attribut disabled">L'attribut disabled</a>
<a href="#L'attribut size">L'attribut size</a>
<a href="#L'attribut maxlength">L'attribut maxlength</a>
<a href="#Les attributs min et max">Les attributs min et max</a>
<a href="#Bibliographie">Bibliographie</a>
