<nav class="tableDesMatieres">
    <a href="#Constantes">Constantes</a>
    <a href="#Expressions conditionnelles">Expressions conditionnelles</a>
    <a href="#Exercice 1">Exercice 1</a>
    <a href="#Exercice 2">Exercice 2</a>
    <a href="#Switch">Switch</a>
    <a href="#Boucles">Boucles</a>
    <a href="#Exercice 3">Exercice 3</a>
    <a href="#Les fonctions">Les fonctions</a>
    <a href="#Créer un tableau en PHP">Créer un tableau en PHP</a>
    <a href="#Exercice 4">Exercice 4</a>
    <a href="#Tableaux associatifs">Tableaux associatifs</a>
    <a href="#Exercice 5">Exercice 5</a>
    <a href="#Tableaux multidimensionnels">Tableaux multidimensionnels</a>
    <a href="#Exercice 6">Exercice 6</a>
    <a href="#Constantes">Constantes</a>
    <a href="#Tableaux de tri">Tableaux de tri</a>
    <a href="#Exercice 7">Exercice 7</a>
    <a href="#Exercice 8">Exercice 8</a>
    <a href="#Exercice 9">Exercice 9</a>
    <a href="#Exercice 10">Exercice 10</a>
    <a href="#Exercice 11">Exercice 11</a>
    <a href="#Dates">Dates</a>
    <a href="#Inclure les fichiers">Inclure les fichiers</a>
    <a href="#La gestion des fichiers">La gestion des fichiers</a>
    <a href="#Créer un fichier">Créer un fichier</a>
    <a href="#Bibliographie">Bibliographie</a>
</nav>