<a href="#HTML">HTML</a>
<a href="#Balise d'en-tête">Balise d'en-tête</a>
<a href="#Balise Paragraph">Balise Paragraph</a>
<a href="#Balise Line Break">Balise Line Break</a>
<a href="#Centrage du contenu">Centrage du contenu</a>
<a href="#Ligne horizontale">Ligne horizontale</a>
<a href="#Conserver la mise en forme">Conserver la mise en forme</a>
<a href="#Nonbreaking spaces">Nonbreaking spaces</a>
<a href="#Element HTML vide">Element HTML vide</a>
<a href="#Attribut HTML">Attribut HTML</a>
<a href="#Attributs de base">Attributs de base</a>
<a href="#L'attribut Id">L'attribut Id</a>
<a href="#L'attribut title">L'attribut title</a>
<a href="#L'attribut class">L'attribut class</a>
<a href="#L'attribut style">L'attribut style</a>
<a href="#L'attribut d'internationalisation">L'attribut d'internationalisation</a>
<a href="#L'attribut dir">L'attribut dir</a>
<a href="#L'attribut lang">L'attribut lang</a>
<a href="#L'attribut xml:lang">L'attribut xml:lang</a>
<a href="#Formatage HTML">Formatage HTML</a>
<a href="#Texte en italique">Texte en italique</a>
<a href="#Texte souligné">Texte souligné</a>
<a href="#Texte en exposant">Texte en exposant</a>
<a href="#Exercice 1">Exercice 1</a>
<a href="#Texte en indice">Texte en indice</a>
<a href="#Texte plus grand">Texte plus grand</a>
<a href="#Texte plus petit">Texte plus petit</a>
<a href="#Texte accentué">Texte accentué</a>
<a href="#Texte marqué">Texte marqué</a>
<a href="#Texte fort">Texte fort</a>
<a href="#Terme spécial">Terme spécial</a>
<a href="#Citation">Citation</a>
<a href="#Code informatique">Code informatique</a>
<a href="#Sortie du programme">Sortie du programme</a>
<a href="#Texte d'adresse">Texte d'adresse</a>
<a href="#Bibliographie">Bibliographie</a>
