<a href="#Objets JavaScript">Objets JavaScript</a>
<a href="#Méthodes d'objet">Méthodes d'objet</a>
<a href="#Événements JavaScript">Événements JavaScript</a>
<a href="#Chaînes de charactères">Chaînes de charactères</a>
<a href="#Longueur de chiane">Longueur de chiane</a>
<a href="#indexOf()">indexOf()</a>
<a href="#lastIndexOf()">lastIndexOf()</a>
<a href="#search()">search()</a>
<a href="#slice()">slice()</a>
<a href="#substring()">substring()</a>
<a href="#replace()">replace()</a>
<a href="#toUpperCase()">toUpperCase()</a>
<a href="#toLowerCase()">toLowerCase()</a>
<a href="#concat()">concat()</a>
<a href="#Opérateur +">Opérateur +</a>
<a href="#trim()">trim()</a>
<a href="#padStart()">padStart()</a>
<a href="#padEnd()">padEnd()</a>
<a href="#charAt()">charAt()</a>
<a href="#charCodeAt()">charCodeAt()</a>
<a href="#Acces à un élément">Acces à un élément</a>
<a href="#Conversion chaine tableau">Conversion chaine tableau</a>
<a href="#Bibliographie">Bibliographie</a>