<a href="#Objets de date">Objets de date</a>
<a href="#Obtention date">Obtention date</a>
<a href="#Affectation date">Affectation Date</a>
<a href="#Objet Mathematique">Objet Mathematique</a>
<a href="#Trigonometrie">Trigonometrie</a>
<a href="#min() et max()">min() et max()</a>
<a href="#random() et log()">Random et Log</a>
<a href="#Operateurs de comparaison">Operateurs de comparaison</a>
<a href="#Structure conditionnelle">If</a>
<a href="#Bibliographie">Bibliographie</a>